---
new_page_extension: md
auto_deploy: false
admin_path: "/static/"
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: src/pages/contact.md
  label: À propos
- type: document
  path: src/pages/catalogue.md
  label: Catalogue
- type: heading
  label: Projets
- type: directory
  path: src/pages/projets
  label: Projets
  create: documents
  match: "**/*"
upload_dir: src/images
public_path: "/src/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: gatsby develop -H 0.0.0.0 -p 8080
  publish_command: gatsby build
  output_directory: public
  preview_command: gatsby build
