---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: src/pages/projets.md
  label: Categories
- type: document
  path: src/pages/contact.md
  label: À propos
- type: document
  path: src/pages/catalogue.md
  label: Catalogue
- type: heading
  label: Projets
- type: directory
  path: src/pages/projets/tables
  label: Tables
  create: documents
  match: "**/*"
  templates:
  - table
- type: directory
  path: src/pages/projets/tables-basses
  label: Tables basses
  create: documents
  match: "**/*"
  templates:
  - projet-table-basse
- type: directory
  path: src/pages/projets/porte-revues
  label: Porte revues
  create: documents
  match: "**/*"
  templates:
  - projet-porte-revue
- type: directory
  path: src/pages/projets/bibliotheques
  label: Bibliothèques
  create: documents
  match: "**/*"
  templates:
  - projet-bibliotheque
- type: directory
  path: src/pages/projets/amenagements-interieurs
  label: Aménagements intérieurs
  create: documents
  match: "**/*"
  templates:
  - projet-amenagements
- type: heading
  label: SEO
- type: document
  path: site-config.json
  label: SEO
upload_dir: src/images
public_path: "/src/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: gatsby develop -H 0.0.0.0 -p 8080
